nblockchain/conventions

.github/workflows/ci.yml
Install everything ourselves instead of using pre-installed images of github.
=> CI: switch to vanilla VMs

commitlint.config.ts, commitlintplugins.test.ts
Fixes https://github.com/nblockchain/conventions/issues/52
=> Find suggestions in a case-insensitive way

commitlint.config.ts, commitlintplugins.test.ts
Fixes https://github.com/nblockchain/conventions/issues/45
=> Ignore body-prose rule when paragraph ends with url

commitlint.config.ts, commitlint/abbreviations.ts, commitlint/plugins.test.ts
Fixes https://github.com/nblockchain/conventions/issues/46
=> No replacement suggestions for the area

.editorconfig, .github/workflows/CI.yml, commitlint.config.ts, commitlint/abbreviations.ts, commitlint/plugins.test.ts
Fixes https://github.com/nblockchain/conventions/issues/49
=> Adopt "prettier" for our TypeScript code

commitlint.config.ts, commitlint/plugins.test.ts
Replaced https://github.com/nblockchain/conventions/pull/11
=> Use Error status for body leading black rule

mixedLineEnding.fsx
Detecting files with mixed line ending.
=> A new feature that detects files with mixed line ending

.github/workflows/CI.yml, .gitignore, conventions.sln, scripts/eofConvention.fsx, scripts/mixedLineEndings.fsx, scripts/shebangConvention.fsx, src/FileConventions.Test/DummyFiles/DummyWithShebang.fsx, src/FileConventions.Test/DummyFiles/DummyWithWrongShebang.fsx, src/FileConventions.Test/DummyFiles/DummyWithoutShebang.fsx, src/FileConventions.Test/FileConventions.Test.fs, src/FileConventions.Test/FileConventions.Test.fsproj, src/FileConventions.Test/Program.fs, src/FileConventions/FileConventions.fsproj, src/FileConventions/Library.fs
Supersedes https://github.com/nblockchain/conventions/pull/29
=>  F# scripts that detects .fsx files without shebang

.github/workflows/CI.yml, commitlint.sh, package.json
Otherwise we get this error in the CI:
```
+ npx commitlint --version
/__w/conventions/conventions/node_modules/@commitlint/load/node_modules/cosmiconfig/dist/index.js:63
const config = metaConfig.config ?? {};
^
SyntaxError: Unexpected token '?'
at wrapSafe (internal/modules/cjs/loader.js:915:16)
at Module._compile (internal/modules/cjs/loader.js:963:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/__w/conventions/conventions/node_modules/@commitlint/load/lib/utils/load-config.js:7:23)
at Module._compile …
```
=> package.json: add, to downgrade cosmiconfig

scripts/eofConvention.fsx, scripts/mixedLineEndings.fsx, scripts/shebangConvention.fsx, scripts/unpinnedDotnetPackageVersions.fsx, scripts/unpinnedGitHubActionsImageVersions.fsx, src/FileConventions/FileConventions.fsproj, src/FileConventions/Helpers.fs
Transfer duplicate code to Helpers.
=> FileConventions/Helpers: add

.github/workflows/CI.yml, scripts/detectNotUsingGitPush1by1.fsx
Fixes https://github.com/nblockchain/conventions/issues/82
=> Add a script to check if gitPush1by1 was used

WorkflowGuidelines.md
This commit descibes some bad practices like DRY, Magic Numbers and Primitive Obsession.
=> WorkflowGuidelines: common bad practices

scripts/detectNotUsingGitPush1by1.fsx
Lacking CI status may be because of not enabling GitHub Actions
or not pushing the commits 1 by 1. The purpose of this commit is
to address these situations separately and display distinct
commit messages based on each scenario.
=> scripts/detectNotUsingGitPush1by1.fsx: improve

commitlint.config.ts, commitlint/plugins.test.ts, commitlint/plugins.ts
Fixes https://github.com/nblockchain/conventions/issues/118
=> Footer note misplacement fix false positive

commitlint/helpers.ts, commitlint/plugins.test.ts, commitlint/plugins.ts
Subceeding min length should never be reported for empty lines.
Fixes https://github.com/nblockchain/conventions/issues/119
Co-authored-by: Parham <parhaamsaremi@gmail.com>
=> Fix bodyParagraphLineMinLength rule

commitlint.config.ts, commitlint/plugins.test.ts, commitlint/plugins.ts
Fixes https://github.com/nblockchain/conventions/issues/125
=> Fix footer-refs-validity false positive

commitlint/helpers.ts, commitlint/plugins.test.ts, commitlint/plugins.ts
Fixes https://github.com/nblockchain/conventions/issues/120
Co-authored-by: `Taras <reg@webwarrior.ws>`
=> commitlint: support unnumbered&numbered bullets

commitlint/testHelpers.ts
Fixes https://github.com/nblockchain/conventions/issues/154
=> testHelpers: fix spawnSync on windows

commitlint/helpers.ts, commitlint/plugins.test.ts
Fixes https://github.com/nblockchain/conventions/issues/148
=> Fix for Issue #148

.github/workflows/CI.yml, commitlint.sh, commitlint/testHelpers.ts
The ones that caused flakiness in the commitlint tests are left out.
=> Reapply majority of npm-related improvements from PR#166

scripts/wrapLatestCommitMsg.fsx, src/FileConventions/Library.fs
Fixes https://github.com/nblockchain/conventions/issues/123
=> FileConventions: fix wrapLatestCommitMsg on Win OS

.github/workflows/CI.yml, fsharplint.json, src/FileConventions.Test/FileConventions.Test.fs, src/FileConventions/Library.fs, src/FileConventions/NugetVersionsCheck.fs
- Upgraded FSharpLint to version 0.26.1--date20250724-0123.git-3924085
- Applied FSharpLint suggestions
=> GithubCI: upgrade FSharpLint to latest version
