commitlint.config.ts
commitlintplugins.test.ts

Existing body-max-line-length rule from commitlint doesn't whitelist URLs so we created a new custom one.

Rule for body max line length

---

commitlint.config.ts
commitlintplugins.test.ts

WIP commits without trailing number might be confusing. This rule forces contributors to add a number after their WIP commit to further distinguish the WIP commits.

Prohibit WIP commits without number

---

commitlint.config.ts
commitlintplugins.test.ts

Messages that start with "Fixes" or "[]" should be in the footer this newly added rule will check this behavior and will raise errors if it's not correctly addressed.

Add rule to check if a footer line is in body

---

commitlint.config.ts
commitlintplugins.test.ts

Prohibit contributors from defining a reference and not putting it in the footer or putting a reference in the footer which is not defined in the body.

Rule to check every reference is used in body and footer

---

.github/workflows/ci.yml
.gitignore
commitlint.sh
package-lock.json
package.json

New version 17.4.0 started failing probably because it brings
a new version of typescript (dependency). Downgrading to 17.3.0
was not possible because @commitlint/types package doesn't seem
to have that version (see https://www.npmjs.com/package/@commitlint/types?activeTab=versions).
I [tried]( https://stackoverflow.com/q/75014308/544947) fixing this with simply adding @17.0.0 to the package
name in the installation command but that would still install
some 17.4.0 version of the dependencies, so I had to install
all dependencies on their 17.0.0 one by one and save the
package.json files as a workaround, in this order:
```
npm install --save @commitlint/types@17.0.0
npm install --save @commitlint/config-validator@17.0.0
npm install --save @commitlint/top-level@17.0.0
npm install --save …
```

commitlint: downgrade to 17.0.0 to fix CI 

---

scripts/detectNotUsingGitPush1by1.fsx

In this script I was using `rev-parse --abbrev-ref HEAD`
command to extract the current branch name. If I run
`git rev-parse --abbrev-ref HEAD` command locally it
will give the current branch name, but in the PR it will
output HEAD, and running `git rev-list HEAD~..HEAD`
sometimes gives the PR commits and sometimes it
doesn't. Here I fixed this behaviour by using github api 
to extract PR commits instead of `git rev-list HEAD~..HEAD`
command.

scripts/detectNotUsingGitPush1by1.fsx: fix

---

WorkflowGuidelines.md

This commit adds the "discarding exceptions" bad practice to the list of bad practices.

WorkflowGuidelines: discarding exceptions

---

ReadMe.md
commitlint.config.ts
commitlint/plugins.test.ts
commitlint/plugins.ts
scripts/wrapLatestCommitMsg.fsx
src/FileConventions.Test/FileConventions.Test.fs
src/FileConventions/Library.fs

Added the wrapLatestCommitMsg.fsx script to wrap the last commit
message while considering code blocks and footer notes including
references, Fixes and Closes and Co-authored by lines.

Add a script to wrap the last commit msg body into a certain character count per line

---

commitlint.config.ts
commitlint/helpers.ts
commitlint/plugins.test.ts
commitlint/plugins.ts

When we have a commit with EOL after "[]" then we get a confusing error about the reference not existing. In this PR I first check if a reference number has no reference and give a different error about it.

Fix error message for footernote references with EOL

---

scripts/detectNotUsingGitPush1by1.fsx

Use ACCESS_TOKEN if available. This is needed for accessing info about CI runs in a fork of a private repo.

scripts: use ACCESS_TOKEN if available

---

.gitignore
commitlint.config.ts
commitlint/helpers.ts
commitlint/plugins.test.ts
commitlint/plugins.ts

Fix for double (2 rules) false positive that happened in
commitlint step of fsx repo [1] ([2]).
[1] https://github.com/nblockchain/fsx/commit/bb58c43a565b4ba717e5f0ce1f1007db7371f546
[2] https://github.com/nblockchain/fsx/actions/runs/5231049113/jobs/9449654778

commitlint: fix double false positive (2 rules)

---

.github/workflows/CI.yml
.gitignore
ReadMe.md
scripts/inconsistentVersionsInFSharpScripts.fsx
scripts/inconsistentVersionsInGitHubCI.fsx
src/FileConventions.Test/DummyFiles/DummyCIWithSamePulumiVersion.yml
src/FileConventions.Test/DummyFiles/DummyCIWithSameSetupPulumiVersion.yml
src/FileConventions.Test/DummyFiles/DummyCIWithSetupPulumiVersionV2.0.0.yml
src/FileConventions.Test/DummyFiles/DummyCIWithSetupPulumiVersionV2.0.1.yml
src/FileConventions.Test/DummyFiles/DummyCIWithoutSameCheckoutVersion.yml
src/FileConventions.Test/DummyFiles/DummyCIWithoutSameNodeVersion.yml
src/FileConventions.Test/DummyFiles/DummyCIWithoutSamePulumiVersion.yml
src/FileConventions.Test/DummyFiles/DummyCIWithoutSameSetupPulumiVersion.yml
src/FileConventions.Test/DummyFiles/DummyFsharpScriptWithFsdkVersion0.6.0.fsx
src/FileConventions.Test/DummyFiles/DummyFsharpScriptWithFsdkVersion0.6.1.fsx
src/FileConventions.Test/DummyFiles/DummyScripts/DummyFsharpScriptWithFsdkVersion0.6.0.fsx
src/FileConventions.Test/DummyFiles/DummyScripts/DummyFsharpScriptWithFsdkVersion0.6.1.fsx
src/FileConventions.Test/DummyFiles/DummyWorkflows/DummyCIWithSetupPulumiVersionV2.0.0.yml
src/FileConventions.Test/DummyFiles/DummyWorkflows/DummyCIWithSetupPulumiVersionV2.0.1.yml
src/FileConventions.Test/FileConventions.Test.fs
src/FileConventions.Test/FileConventions.Test.fsproj
src/FileConventions/Library.fs

Superseded https://github.com/nblockchain/conventions/pull/85

Detect inconsistent (e.g. pulumi) versions in GitHubCI and (e.g. nuget pkgs versions) in fsx scripts

---

.github/workflows/CI.yml
scripts/checkCommits1by1.fsx

Improve this fsx script to also detect commits with bad CI
status. That is, if commit msg contains text "failing test"
then it would be allowed to have broken CI, else CI should be
green.
Fixes https://github.com/nblockchain/conventions/issues/95

scripts/checkCommits1by1.fsx: augment

---

scripts/checkCommits1by1.fsx

Improve the error message to state that if a commit is adding a failing test, it should contain the `failing test` phrase in its message.

scripts/checkCommits1by1.fsx: improve error msg

---

commitlint/plugins.test.ts
commitlint/plugins.ts

Add tests for case described in https://github.com/nblockchain/conventions/issues/124.
Add exception to bodySoftMaxLineLength function when line exceeds max length but ends with a git commit hash.
Fixes https://github.com/nblockchain/conventions/issues/124

Body soft max line length exception

---

commitlint/helpers.ts
commitlint/plugins.test.ts

The `replace()` method does not replace all. Use `replaceall()` to resolve issue #134 .

Fix body prose false positive

---

scripts/wrapLatestCommitMsg.fsx

The wrapLatestCommitMsg.fsx script added a new line after the body. This new line is removed in this commit.
Fixes https://github.com/nblockchain/conventions/issues/116

scripts: fix wrapLatestCommitMsg's output commit

---

.github/workflows/CI.yml
commitlint/integration.test.ts
commitlint/plugins.test.ts
commitlint/plugins.ts
commitlint/testHelpers.ts
tsconfig.json

Add "compile typescript" step to CI so that any compiler errors in tests are reported rather than lead to test failure with unclear cause.

CI: add compile typescript step

---

commitlint/helpers.ts
docs/WorkflowGuidelines.md

The workflow guidelines state that we should avoid the keyword "undefined". This is also extra good because it seems that the ? guards against both null and undefined, at least according to this example:
https://github.com/conventional-changelog/commitlint/commit/7ab4bab31f4b19ddedd850e435398037437007b6

commitlint: honor our own WorkflowGuidelines

---

scripts/unpinnedNugetPackageReferenceVersionsInProjects.fsx

Use working dir instead of script's parent directory in unpinnedNugetPackageReferenceVersionsInProjects.fsx to search for projects as it is intended behavior.

scripts: fix unpinnedNugetPackage... script

---

src/FileConventions.Test/DummyFiles/DummyWorkflowsWithEnvPrefixed/DummyCIWithPulumiVersionInEnvPrefixedV2.0.0.yml
src/FileConventions.Test/DummyFiles/DummyWorkflowsWithEnvPrefixed/DummyCIWithPulumiVersionInEnvPrefixedV2.0.1.yml
src/FileConventions.Test/FileConventions.Test.fs
src/FileConventions/Library.fs

When chceking versions in yaml files, correctly process case when environment variable is referenced using `env.` prefix, e.g. `env.FOO`.

FileConventions: account for .env prefix when checking versions in yaml files

---

scripts/executableConvention.fsx

Include *.sh files in executable permission check script. Also Use working dir instead of script's parent directory in that script.

scripts: include *.sh files in executable check

---

.github/workflows/CI.yml

Because 23.10 is no longer supported and 24.04 is LTS release.

GithubCI: use Ubuntu 24.04 instead of 23.10

---

docs/WorkflowGuidelines.md

Added point about avoiding usage of JavaScript/TypeScript spread operator (`...`).

docs: expanded bad practices section

---

ReadMe.md
scripts/inconsistentNugetVersionsInDotNetProjectsAndFSharpScripts.fsx
src/FileConventions/CombinedVersionCheck.fs

To search for .fsx and project files in combined versions check script. If no arguments are passed, current working directory is used.

scripts,FileConventions: allow specifying dirs

---

src/FileConventions.Test/WrapTextTests.fs
src/FileConventions/Library.fs

Ignore codeblocks while splitting the text into paragraphs because there might be a codeblock with multiple paragraphs.
Fixes https://github.com/nblockchain/conventions/issues/117
Supersedes https://github.com/nblockchain/conventions/pull/135

FileConventions: fix WrapText function

---

.github/workflows/CI.yml
commitlint.config.ts
commitlint/abbreviations.ts
commitlint/fpHelpers.ts
commitlint/helpers.ts
commitlint/plugins.ts
commitlint/tests/integration.test.ts
commitlint/tests/plugins.test.ts
commitlint/tests/testHelpers.ts
eslint.config.mjs

Installed typescript-eslint and added CI step to run it.
Ran `npx eslint . --fix`. It replaced `let` declarations with `const` ones when value is not reassigned.
Fixed some other eslint warnings. Silenced remaining warnings.
Fixed type error that appeared because of using typed imports in testHelpers.ts.
Fixes https://github.com/nblockchain/conventions/issues/173

GithubCI: install and run typescript-eslint

---

scripts/checkCommits1by1.fsx

When checking for CI status, discard check suites for the commit that are not from PR branch. Otherwise the script can report error when there is none in case the same commit is also present in different branch.

scripts: only check PR branch in checkCommits1by1

---

.github/workflows/CI.yml

To avoid version conflict with `@typescript-eslint/eslint-plugin@8.38.0` (it requires typescript <5.9.0 and latest stable typescript version is 5.9.2).

GithubCI: pin TypeScript version to 5.8.3

---

scripts/inconsistentNugetVersionsInFSharpScripts.fsx

When checking for inconsistent versions of Nuget packages in fsx scripts, because it might produce false positives if conventions repository is inside working directory.

scripts: exclude files in conventions repository
